-------------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2004 Brian Bruns
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-------------------------------------------------------------

DROP TABLE SPPSZ_ATTR_ALL;
CREATE TABLE SPPSZ_ATTR_ALL
 (
	VALUE			Int8, 
	FCID			Int8, 
	MAP_SOURCE			varchar (8), 
	ESLF_CODE			Int4, 
	ESLF_NAME			varchar (300), 
	DATA_SOURCE			varchar (40), 
	ASSESSMENT_YEAR			Int4, 
	STATE			varchar (4), 
	HALF_STATE			varchar (6), 
	CNTY			Int2, 
	PLOT			Int8, 
	OCCASION_NUM			Int2, 
	IDB_PLOT_ID			Int8, 
	BAC_GE_3			double precision, 
	BAC_PROP			double precision, 
	BAC_3_25			double precision, 
	BAC_25_50			double precision, 
	BAC_50_75			double precision, 
	BAC_75_100			double precision, 
	BAC_GE_100			double precision, 
	BAH_GE_3			double precision, 
	BAH_PROP			double precision, 
	BAH_3_25			double precision, 
	BAH_25_50			double precision, 
	BAH_50_75			double precision, 
	BAH_75_100			double precision, 
	BAH_GE_100			double precision, 
	BAA_GE_3			double precision, 
	BAA_3_25			double precision, 
	BAA_25_50			double precision, 
	BAA_50_75			double precision, 
	BAA_75_100			double precision, 
	BAA_GE_100			double precision, 
	BPH_GE_3			double precision, 
	TPH_GE_3			double precision, 
	TPH_3_25			double precision, 
	TPH_25_50			double precision, 
	TPH_50_75			double precision, 
	TPH_75_100			double precision, 
	TPH_GE_100			double precision, 
	TPHC_GE_3			double precision, 
	TPHC_GE_50			double precision, 
	TPHC_GE_75			double precision, 
	TPHC_GE_100			double precision, 
	TPHH_GE_3			double precision, 
	TPHTOL_GE_3			double precision, 
	TPHINTOL_GE_3			double precision, 
	VPH_GE_3			double precision, 
	VPH_3_25			double precision, 
	VPH_25_50			double precision, 
	VPH_50_75			double precision, 
	VPH_75_100			double precision, 
	VPH_GE_100			double precision, 
	VPHC_GE_3			double precision, 
	VPHH_GE_3			double precision, 
	QMDC_DOM			double precision, 
	QMDH_DOM			double precision, 
	QMDA_DOM			double precision, 
	QMDC_GE_3			double precision, 
	QMDH_GE_3			double precision, 
	QMDA_GE_3			double precision, 
	QMDC_75PCT			double precision, 
	MNDBHBA_ALL			double precision, 
	MNDBHBA_CON			double precision, 
	MNDBHBA_HDW			double precision, 
	STPH_12_25			double precision, 
	STPH_25_50			double precision, 
	STPH_50_75			double precision, 
	STPH_75_100			double precision, 
	STPH_GE_12			double precision, 
	STPH_GE_25			double precision, 
	STPH_GE_50			double precision, 
	STPH_GE_75			double precision, 
	STPH_GE_100			double precision, 
	SVPH_12_25			double precision, 
	SVPH_25_50			double precision, 
	SVPH_50_75			double precision, 
	SVPH_75_100			double precision, 
	SVPH_GE_12			double precision, 
	SVPH_GE_25			double precision, 
	SVPH_GE_50			double precision, 
	SVPH_GE_75			double precision, 
	SVPH_GE_100			double precision, 
	SBPH_5_9_IN			double precision, 
	SBPH_9_20_IN			double precision, 
	SBPH_GE_20_IN			double precision, 
	SBPH_GE_12			double precision, 
	DVPH_12_25			double precision, 
	DVPH_25_50			double precision, 
	DVPH_50_75			double precision, 
	DVPH_75_100			double precision, 
	DVPH_GE_12			double precision, 
	DVPH_GE_25			double precision, 
	DVPH_GE_50			double precision, 
	DVPH_GE_75			double precision, 
	DVPH_GE_100			double precision, 
	DCOV_12_25			double precision, 
	DCOV_25_50			double precision, 
	DCOV_50_75			double precision, 
	DCOV_75_100			double precision, 
	DCOV_GE_12			double precision, 
	DCOV_GE_25			double precision, 
	DCOV_GE_50			double precision, 
	DCOV_GE_75			double precision, 
	DCOV_GE_100			double precision, 
	CANCOV			double precision, 
	CANCOV_CON			double precision, 
	CANCOV_HDW			double precision, 
	CANCOV_DOM			double precision, 
	STNDHGT			double precision, 
	HCB			double precision, 
	SDDBH			double precision, 
	SDBA			double precision, 
	SDI			double precision, 
	SDI_REINEKE			double precision, 
	CONR			Int2, 
	HDWR			Int2, 
	TREER			Int2, 
	IV_CON			double precision, 
	IV_HDW			double precision, 
	IV_VS			double precision, 
	IV_100			double precision, 
	DDI			double precision, 
	AGE_DOM			double precision, 
	AGE_DOM_NO_REM			double precision, 
	TPH_REML			double precision, 
	VPH_REML			double precision, 
	REM_PCTL			double precision, 
	TPH_REMS			double precision, 
	VPH_REMS			double precision, 
	REM_PCTS			double precision, 
	VPH_REMD			double precision, 
	REM_PCTD			double precision, 
	STRUCCOND			Int2, 
	VEGCLASS			Int2, 
	STRUCCONDR			Int2, 
	VEGCLASSR			Int2, 
	CONPLBA			varchar (20), 
	CONPLIV			varchar (20), 
	CONPLCOV			varchar (20), 
	HDWPLBA			varchar (20), 
	HDWPLIV			varchar (20), 
	HDWPLCOV			varchar (20), 
	UPLCOV			varchar (20), 
	FORTYPBA			varchar (42), 
	FORTYPIV			varchar (42), 
	FORTYPCOV			varchar (42), 
	SIZECL			Int2, 
	COVCL			Int2, 
	SC			Int2, 
	SC_DECAID			varchar (2), 
	IMAP_DOMSPP			varchar (20), 
	IMAP_LAYERS			Int2, 
	IMAP_QMD			double precision, 
	VC_QMDA			Int2, 
	VC_QMDC			Int2, 
	LSOG			varchar (2), 
	LSOG_TPHC_50			varchar (2), 
	OGSI			double precision
);
-- CREATE ANY INDEXES ...



-- CREATE ANY Relationships ...

-- relationships are not supported for postgres
