# Generated by Django 2.2.12 on 2020-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
