# Generated by Django 2.2.12 on 2020-07-13 16:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0003_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxlot',
            options={'verbose_name': 'Taxlot', 'verbose_name_plural': 'Taxlots'},
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='geometry_final',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='geometry_orig',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='manipulators',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='sharing_groups',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='user',
        ),
        migrations.AddField(
            model_name='taxlot',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Grid Cell Geometry'),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
