# Generated by Django 2.2.12 on 2020-07-30 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import landmapper.models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0004_auto_20200713_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='aerial_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='property',
            name='forest_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='property',
            name='report_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=landmapper.models.Property.report_default, verbose_name='report_data'),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='property',
            name='stream_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='property',
            name='street_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='property',
            name='terrain_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
