# Generated by Django 2.2.12 on 2020-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0005_auto_20200730_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_map_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
