# Generated by Django 2.2.12 on 2020-08-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0007_property_scalebar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxlot',
            name='acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='agency',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='elev_max',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='elev_max_1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='elev_min',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='elev_min_1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='frstdivno',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='huc12',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='max_elevation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='mean_elevation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='min_elevation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='odf_fpd',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='orzdesc',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='rangeno',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='twnshpno',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
