# Generated by Django 2.2.12 on 2020-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0008_auto_20200810_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='header',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Popup Header'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Popup Body'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Menu Item'),
        ),
    ]
