# Generated by Django 2.2.12 on 2020-10-05 16:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0009_auto_20201005_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Popup Body'),
        ),
    ]
