# Generated by Django 2.2.12 on 2020-10-28 14:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0011_auto_20201026_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukey', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('areasym', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('spatial', models.FloatField(blank=True, default=None, null=True)),
                ('musym', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('shp_lng', models.FloatField(blank=True, default=None, null=True)),
                ('shap_ar', models.FloatField(blank=True, default=None, null=True)),
                ('avgsi', models.FloatField(blank=True, default=None, null=True)),
                ('muname', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('drclssd', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('frphrtd', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('avg_rs_l', models.FloatField(blank=True, default=None, null=True)),
                ('avg_rs_h', models.FloatField(blank=True, default=None, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Grid Cell Geometry')),
            ],
        ),
    ]
