# Generated by Django 2.2.12 on 2020-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0012_soiltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxlot',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
