# Generated by Django 2.2.12 on 2020-11-03 12:56

from django.db import migrations

def migrate_pk_to_uuid(apps, schema_editor):
    taxlot = apps.get_model('landmapper', 'Taxlot')
    for lot in taxlot.objects.all():
        lot.uuid = str(lot.pk)
        lot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0013_taxlot_uuid'),
    ]

    operations = [
        migrations.RunPython(migrate_pk_to_uuid),
    ]
