# Generated by Django 2.2.12 on 2020-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0014_auto_20201103_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxlot',
            name='uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
