# Generated by Django 2.2.12 on 2020-11-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0016_remove_taxlot_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxlot',
            name='acres',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='area',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='rangedir',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='shape_leng',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='twnshpdir',
        ),
        migrations.AddField(
            model_name='taxlot',
            name='legal_label',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
