# Generated by Django 2.2.12 on 2021-07-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0018_auto_20201205_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxlot',
            name='frstdivno',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='mean_elevation',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='rangeno',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='twnshplab',
        ),
        migrations.RemoveField(
            model_name='taxlot',
            name='twnshpno',
        ),
        migrations.AddField(
            model_name='taxlot',
            name='county',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='map_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='map_taxlot',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxlot',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
