# Generated by Django 2.2.12 on 2021-04-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0018_auto_20201205_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_map_image_509x722',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
