# Generated by Django 2.2.12 on 2021-07-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0020_auto_20210412_1010'),
        ('landmapper', '0019_auto_20210707_1147'),
    ]

    operations = [
    ]
