# Generated by Django 2.2.12 on 2021-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0021_merge_20210707_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soiltype',
            name='avgsi',
        ),
        migrations.AddField(
            model_name='soiltype',
            name='si_label',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
