# Generated by Django 2.2.12 on 2021-07-14 16:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0022_auto_20210708_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='city', max_length=100)),
                ('state', models.CharField(default='OR', max_length=30)),
                ('population', models.IntegerField()),
                ('place_fips', models.IntegerField()),
                ('density_sqmi', models.FloatField(blank=True, default=None, null=True)),
                ('area_sqmi', models.FloatField(blank=True, default=None, null=True)),
                ('population_class', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857, verbose_name='Population Center Geometry')),
            ],
        ),
    ]
