# Generated by Django 2.2.12 on 2021-07-26 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0023_populationpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foresttype',
            name='name',
        ),
        migrations.AddField(
            model_name='foresttype',
            name='can_class',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cover Class'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='can_cr_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Canopy Cover Max Range'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='can_cr_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Canopy Cover Min Range'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='can_h_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Canopy Height Max'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='can_h_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Canopy Height Min'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='comp_ab',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Abundant Species'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='comp_min',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Minor Species'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='comp_over',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Overall Composition'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='diameter',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Tree Size Class'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Grid Cell Geometry'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='symbol',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='tree_r_max',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Tree Size Est. Range Max'),
        ),
        migrations.AddField(
            model_name='foresttype',
            name='tree_r_min',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Tree Size Est. Range Min'),
        ),
    ]
