# Generated by Django 2.2.12 on 2021-12-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0024_auto_20210726_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foresttype',
            name='can_cr_max',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='can_cr_min',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='can_h_max',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='can_h_min',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='comp_ab',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='comp_min',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='comp_over',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='tree_r_max',
        ),
        migrations.RemoveField(
            model_name='foresttype',
            name='tree_r_min',
        ),
        migrations.AddField(
            model_name='foresttype',
            name='fortype',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Forest Type'),
        ),
        migrations.AlterField(
            model_name='foresttype',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
