# Generated by Django 3.2.14 on 2023-02-28 10:25

from django.db import migrations, models
import landmapper.models


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0027_profile_twoweekfollowupsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='report_data',
            field=models.JSONField(default=landmapper.models.Property.report_default, verbose_name='report_data'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='record_taxlots',
            field=models.JSONField(default=landmapper.models.PropertyRecord.taxlots_default, verbose_name='record_taxlots'),
        ),
    ]
