# Generated by Django 3.2.14 on 2023-02-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmapper', '0028_auto_20230228_1025'),
        ('landmapper', '0028_person'),
    ]

    operations = [
    ]
