# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Adding model 'Stand'
        db.create_table('trees_stand', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user', self.gf('django.db.models.fields.related.ForeignKey')(related_name='trees_stand_related', to=orm['auth.User'])),
            ('name', self.gf('django.db.models.fields.CharField')(max_length='255')),
            ('date_created', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('date_modified', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('content_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='trees_stand_related', null=True, to=orm['contenttypes.ContentType'])),
            ('object_id', self.gf('django.db.models.fields.PositiveIntegerField')(null=True, blank=True)),
            ('manipulators', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('geometry_orig', self.gf('django.contrib.gis.db.models.fields.PolygonField')(srid=3857, null=True, blank=True)),
            ('geometry_final', self.gf('django.contrib.gis.db.models.fields.PolygonField')(srid=3857, null=True, blank=True)),
            ('rx', self.gf('django.db.models.fields.CharField')(default='--', max_length=2)),
            ('domspp', self.gf('django.db.models.fields.CharField')(default='--', max_length=2)),
        ))
        db.send_create_signal('trees', ['Stand'])

        # Adding M2M table for field sharing_groups on 'Stand'
        db.create_table('trees_stand_sharing_groups', (
            ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True)),
            ('stand', models.ForeignKey(orm['trees.stand'], null=False)),
            ('group', models.ForeignKey(orm['auth.group'], null=False))
        ))
        db.create_unique('trees_stand_sharing_groups', ['stand_id', 'group_id'])

        # Adding model 'ForestProperty'
        db.create_table('trees_forestproperty', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user', self.gf('django.db.models.fields.related.ForeignKey')(related_name='trees_forestproperty_related', to=orm['auth.User'])),
            ('name', self.gf('django.db.models.fields.CharField')(max_length='255')),
            ('date_created', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('date_modified', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('content_type', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='trees_forestproperty_related', null=True, to=orm['contenttypes.ContentType'])),
            ('object_id', self.gf('django.db.models.fields.PositiveIntegerField')(null=True, blank=True)),
            ('geometry_final', self.gf('django.contrib.gis.db.models.fields.PolygonField')(srid=3857)),
        ))
        db.send_create_signal('trees', ['ForestProperty'])

        # Adding M2M table for field sharing_groups on 'ForestProperty'
        db.create_table('trees_forestproperty_sharing_groups', (
            ('id', models.AutoField(verbose_name='ID', primary_key=True, auto_created=True)),
            ('forestproperty', models.ForeignKey(orm['trees.forestproperty'], null=False)),
            ('group', models.ForeignKey(orm['auth.group'], null=False))
        ))
        db.create_unique('trees_forestproperty_sharing_groups', ['forestproperty_id', 'group_id'])

        # Adding model 'Parcel'
        db.create_table('trees_parcel', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('apn', self.gf('django.db.models.fields.CharField')(max_length=40)),
            ('geom', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=3857)),
        ))
        db.send_create_signal('trees', ['Parcel'])

        # Adding model 'StreamBuffer'
        db.create_table('trees_streambuffer', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('area', self.gf('django.db.models.fields.FloatField')()),
            ('perimeter', self.gf('django.db.models.fields.FloatField')()),
            ('str_buf_field', self.gf('django.db.models.fields.IntegerField')()),
            ('str_buf_id', self.gf('django.db.models.fields.IntegerField')()),
            ('inside', self.gf('django.db.models.fields.IntegerField')()),
            ('geom', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=3857)),
        ))
        db.send_create_signal('trees', ['StreamBuffer'])

        # Adding model 'County'
        db.create_table('trees_county', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('fips', self.gf('django.db.models.fields.IntegerField')()),
            ('cntyname', self.gf('django.db.models.fields.CharField')(max_length=23)),
            ('polytype', self.gf('django.db.models.fields.IntegerField')()),
            ('stname', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('soc_cnty', self.gf('django.db.models.fields.IntegerField')()),
            ('cnty_fips', self.gf('django.db.models.fields.IntegerField')()),
            ('st_fips', self.gf('django.db.models.fields.IntegerField')()),
            ('geom', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=3857)),
        ))
        db.send_create_signal('trees', ['County'])

        # Adding model 'FVSVariant'
        db.create_table('trees_fvsvariant', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('code', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('fvsvariant', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('geom', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=3857)),
        ))
        db.send_create_signal('trees', ['FVSVariant'])

        # Adding model 'FVSSpecies'
        db.create_table('trees_fvsspecies', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('usda', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('fia', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('fvs', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('common', self.gf('django.db.models.fields.TextField')()),
            ('scientific', self.gf('django.db.models.fields.TextField')()),
            ('AK', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('BM', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('CA', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('CI', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('CR', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('EC', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('EM', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('IE', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('KT', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('NC', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('NI', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('PN', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('SO', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('TT', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('UT', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('WC', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('WS', self.gf('django.db.models.fields.CharField')(max_length=2)),
        ))
        db.send_create_signal('trees', ['FVSSpecies'])

        # Adding model 'TreeLive'
        db.create_table(u'tree_live', (
            ('live_id', self.gf('django.db.models.fields.BigIntegerField')(primary_key=True)),
            ('pntid', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('ccid', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('fcid', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('pltid', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('loc_id', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('pnt_num', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('plot_type', self.gf('django.db.models.fields.CharField')(max_length=40, blank=True)),
            ('data_source', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True)),
            ('source_db', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True)),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=4, blank=True)),
            ('plot', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('assessment_date', self.gf('django.db.models.fields.DateTimeField')(null=True, blank=True)),
            ('spp_symbol', self.gf('django.db.models.fields.CharField')(max_length=20, blank=True)),
            ('scientific_name', self.gf('django.db.models.fields.CharField')(max_length=200, blank=True)),
            ('con', self.gf('django.db.models.fields.CharField')(max_length=2, blank=True)),
            ('dbh_cm', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dbh_class', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dbh_est_method', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('ba_m2', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('ht_m', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('ht_est_method', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('mod_htm_fvs', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('for_spec', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('age_bh', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('crown_class', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('crown_ratio', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('hcb', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('ucc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vol_m3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('cull_cubic', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('plot_size', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('tree_count', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('source_id', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('baph_pnt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baph_cc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baph_fc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baph_plt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_pnt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_cc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_fc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_plt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('pctcov_pnt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('pctcov_cc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('pctcov_fc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('pctcov_plt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('rem_pnt', self.gf('django.db.models.fields.CharField')(max_length=2, blank=True)),
            ('rem_cc', self.gf('django.db.models.fields.CharField')(max_length=2, blank=True)),
            ('rem_fc', self.gf('django.db.models.fields.CharField')(max_length=2, blank=True)),
            ('rem_plt', self.gf('django.db.models.fields.CharField')(max_length=2, blank=True)),
            ('volph_pnt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('volph_cc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('volph_fc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('volph_plt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_pnt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_cc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_fc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_plt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('biomph_pnt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('biomph_cc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('biomph_fc', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('biomph_plt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
        ))
        db.send_create_signal('trees', ['TreeLive'])

        # Adding model 'PlotSummary'
        db.create_table(u'sppsz_attr_all', (
            ('fcid', self.gf('django.db.models.fields.BigIntegerField')(primary_key=True)),
            ('value', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('map_source', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('eslf_code', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('eslf_name', self.gf('django.db.models.fields.CharField')(max_length=300, null=True, blank=True)),
            ('data_source', self.gf('django.db.models.fields.CharField')(max_length=40, null=True, blank=True)),
            ('assessment_year', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=4, null=True, blank=True)),
            ('half_state', self.gf('django.db.models.fields.CharField')(max_length=6, null=True, blank=True)),
            ('cnty', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('plot', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('occasion_num', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('idb_plot_id', self.gf('django.db.models.fields.BigIntegerField')(null=True, blank=True)),
            ('bac_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bac_prop', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bac_3_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bac_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bac_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bac_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bac_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_prop', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_3_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bah_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baa_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baa_3_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baa_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baa_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baa_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('baa_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('bph_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_3_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphc_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphc_ge_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphc_ge_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphc_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphh_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphtol_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tphintol_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_3_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vphc_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vphh_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmdc_dom', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmdh_dom', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmda_dom', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmdc_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmdh_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmda_ge_3', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('qmdc_75pct', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('mndbhba_all', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('mndbhba_con', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('mndbhba_hdw', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_12_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_ge_12', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_ge_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_ge_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_ge_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stph_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_12_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_ge_12', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_ge_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_ge_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_ge_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('svph_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sbph_5_9_in', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sbph_9_20_in', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sbph_ge_20_in', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sbph_ge_12', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_12_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_ge_12', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_ge_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_ge_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_ge_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dvph_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_12_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_25_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_50_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_75_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_ge_12', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_ge_25', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_ge_50', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_ge_75', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dcov_ge_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('cancov', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('cancov_con', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('cancov_hdw', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('cancov_dom', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('stndhgt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('hcb', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sddbh', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sdba', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sdi', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('sdi_reineke', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('conr', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('hdwr', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('treer', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('iv_con', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_hdw', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_vs', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iv_100', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('ddi', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('age_dom', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('age_dom_no_rem', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_reml', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_reml', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('rem_pctl', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('tph_rems', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_rems', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('rem_pcts', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vph_remd', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('rem_pctd', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('struccond', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('vegclass', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('struccondr', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('vegclassr', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('conplba', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('conpliv', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('conplcov', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('hdwplba', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('hdwpliv', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('hdwplcov', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('uplcov', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('fortypba', self.gf('django.db.models.fields.CharField')(max_length=42, null=True, blank=True)),
            ('fortypiv', self.gf('django.db.models.fields.CharField')(max_length=42, null=True, blank=True)),
            ('fortypcov', self.gf('django.db.models.fields.CharField')(max_length=42, null=True, blank=True)),
            ('sizecl', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('covcl', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('sc', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('sc_decaid', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('imap_domspp', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('imap_layers', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('imap_qmd', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('vc_qmda', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('vc_qmdc', self.gf('django.db.models.fields.SmallIntegerField')(null=True, blank=True)),
            ('lsog', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('lsog_tphc_50', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('ogsi', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
        ))
        db.send_create_signal('trees', ['PlotSummary'])


    def backwards(self, orm):
        
        # Deleting model 'Stand'
        db.delete_table('trees_stand')

        # Removing M2M table for field sharing_groups on 'Stand'
        db.delete_table('trees_stand_sharing_groups')

        # Deleting model 'ForestProperty'
        db.delete_table('trees_forestproperty')

        # Removing M2M table for field sharing_groups on 'ForestProperty'
        db.delete_table('trees_forestproperty_sharing_groups')

        # Deleting model 'Parcel'
        db.delete_table('trees_parcel')

        # Deleting model 'StreamBuffer'
        db.delete_table('trees_streambuffer')

        # Deleting model 'County'
        db.delete_table('trees_county')

        # Deleting model 'FVSVariant'
        db.delete_table('trees_fvsvariant')

        # Deleting model 'FVSSpecies'
        db.delete_table('trees_fvsspecies')

        # Deleting model 'TreeLive'
        db.delete_table(u'tree_live')

        # Deleting model 'PlotSummary'
        db.delete_table(u'sppsz_attr_all')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2012, 4, 16, 15, 2, 22, 906737)'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2012, 4, 16, 15, 2, 22, 906642)'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'trees.county': {
            'Meta': {'object_name': 'County'},
            'cnty_fips': ('django.db.models.fields.IntegerField', [], {}),
            'cntyname': ('django.db.models.fields.CharField', [], {'max_length': '23'}),
            'fips': ('django.db.models.fields.IntegerField', [], {}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'polytype': ('django.db.models.fields.IntegerField', [], {}),
            'soc_cnty': ('django.db.models.fields.IntegerField', [], {}),
            'st_fips': ('django.db.models.fields.IntegerField', [], {}),
            'stname': ('django.db.models.fields.CharField', [], {'max_length': '2'})
        },
        'trees.forestproperty': {
            'Meta': {'object_name': 'ForestProperty'},
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_forestproperty_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'geometry_final': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_forestproperty_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_forestproperty_related'", 'to': "orm['auth.User']"})
        },
        'trees.fvsspecies': {
            'AK': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'BM': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'CA': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'CI': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'CR': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'EC': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'EM': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'IE': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'KT': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'Meta': {'object_name': 'FVSSpecies'},
            'NC': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'NI': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'PN': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'SO': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'TT': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'UT': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'WC': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'WS': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'common': ('django.db.models.fields.TextField', [], {}),
            'fia': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'fvs': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'scientific': ('django.db.models.fields.TextField', [], {}),
            'usda': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'})
        },
        'trees.fvsvariant': {
            'Meta': {'object_name': 'FVSVariant'},
            'code': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'fvsvariant': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'trees.parcel': {
            'Meta': {'object_name': 'Parcel'},
            'apn': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'trees.plotsummary': {
            'Meta': {'object_name': 'PlotSummary', 'db_table': "u'sppsz_attr_all'"},
            'age_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'age_dom_no_rem': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'assessment_year': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'baa_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_3_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_3_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_prop': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_3_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_prop': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bph_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cancov': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cancov_con': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cancov_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cancov_hdw': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cnty': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'conplba': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'conplcov': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'conpliv': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'conr': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'covcl': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'data_source': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True', 'blank': 'True'}),
            'dcov_12_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_ge_12': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_ge_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_ge_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dcov_ge_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ddi': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_12_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_ge_12': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_ge_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_ge_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dvph_ge_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'eslf_code': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'eslf_name': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True', 'blank': 'True'}),
            'fcid': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'}),
            'fortypba': ('django.db.models.fields.CharField', [], {'max_length': '42', 'null': 'True', 'blank': 'True'}),
            'fortypcov': ('django.db.models.fields.CharField', [], {'max_length': '42', 'null': 'True', 'blank': 'True'}),
            'fortypiv': ('django.db.models.fields.CharField', [], {'max_length': '42', 'null': 'True', 'blank': 'True'}),
            'half_state': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'hcb': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'hdwplba': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'hdwplcov': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'hdwpliv': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'hdwr': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'idb_plot_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'imap_domspp': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'imap_layers': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'imap_qmd': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_con': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_hdw': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_vs': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'lsog': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'lsog_tphc_50': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'map_source': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'mndbhba_all': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mndbhba_con': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mndbhba_hdw': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'occasion_num': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ogsi': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'plot': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'qmda_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmda_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdc_75pct': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdc_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdc_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdh_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdh_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'rem_pctd': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'rem_pctl': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'rem_pcts': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sbph_5_9_in': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sbph_9_20_in': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sbph_ge_12': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sbph_ge_20_in': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sc': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sc_decaid': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'sdba': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sddbh': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sdi': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sdi_reineke': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sizecl': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'stndhgt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_12_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_ge_12': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_ge_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_ge_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stph_ge_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'struccond': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'struccondr': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'svph_12_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_ge_12': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_ge_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_ge_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'svph_ge_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_3_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_reml': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_rems': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphc_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphc_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphc_ge_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphc_ge_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphh_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphintol_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tphtol_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'treer': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'uplcov': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'value': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vc_qmda': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vc_qmdc': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vegclass': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vegclassr': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vph_25_50': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_3_25': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_50_75': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_75_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_ge_100': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_remd': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_reml': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vph_rems': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vphc_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vphh_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'})
        },
        'trees.stand': {
            'Meta': {'object_name': 'Stand'},
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_stand_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'domspp': ('django.db.models.fields.CharField', [], {'default': "'--'", 'max_length': '2'}),
            'geometry_final': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'geometry_orig': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'manipulators': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rx': ('django.db.models.fields.CharField', [], {'default': "'--'", 'max_length': '2'}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_stand_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_stand_related'", 'to': "orm['auth.User']"})
        },
        'trees.streambuffer': {
            'Meta': {'object_name': 'StreamBuffer'},
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inside': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'str_buf_field': ('django.db.models.fields.IntegerField', [], {}),
            'str_buf_id': ('django.db.models.fields.IntegerField', [], {})
        },
        'trees.treelive': {
            'Meta': {'object_name': 'TreeLive', 'db_table': "u'tree_live'"},
            'age_bh': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'assessment_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'ba_m2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baph_cc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baph_fc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baph_plt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baph_pnt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'biomph_cc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'biomph_fc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'biomph_plt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'biomph_pnt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ccid': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'con': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'}),
            'crown_class': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'crown_ratio': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cull_cubic': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'data_source': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'dbh_class': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dbh_cm': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dbh_est_method': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'fcid': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'for_spec': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'hcb': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ht_est_method': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ht_m': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_cc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_fc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_plt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'iv_pnt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'live_id': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'}),
            'loc_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mod_htm_fvs': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pctcov_cc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'pctcov_fc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'pctcov_plt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'pctcov_pnt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'plot': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'plot_size': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'plot_type': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'pltid': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pnt_num': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pntid': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rem_cc': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'}),
            'rem_fc': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'}),
            'rem_plt': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'}),
            'rem_pnt': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'}),
            'scientific_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'blank': 'True'}),
            'source_db': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'source_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'spp_symbol': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '4', 'blank': 'True'}),
            'tph_cc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_fc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_plt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_pnt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tree_count': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ucc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vol_m3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'volph_cc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'volph_fc': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'volph_plt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'volph_pnt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['trees']
