# Generated by Django 2.2.12 on 2020-04-29 13:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbongroup',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_carbongroup_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='forestproperty',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_forestproperty_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='myrx',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_myrx_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='input_rxs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Prescriptions associated with each stand'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_scenario_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='scenariostand',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_scenariostand_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_stand_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='strata',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='trees_strata_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
    ]
