# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding field 'ScenarioStand.rx_internal_num'
        db.add_column('trees_scenariostand', 'rx_internal_num',
                      self.gf('django.db.models.fields.IntegerField')(null=True, blank=True),
                      keep_default=False)


    def backwards(self, orm):
        # Deleting field 'ScenarioStand.rx_internal_num'
        db.delete_column('trees_scenariostand', 'rx_internal_num')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'trees.conditionvariantlookup': {
            'Meta': {'object_name': 'ConditionVariantLookup'},
            'cond_id': ('django.db.models.fields.BigIntegerField', [], {'db_index': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'variant_code': ('django.db.models.fields.CharField', [], {'max_length': '2'})
        },
        'trees.county': {
            'Meta': {'object_name': 'County'},
            'cnty_fips': ('django.db.models.fields.IntegerField', [], {}),
            'cntyname': ('django.db.models.fields.CharField', [], {'max_length': '23'}),
            'fips': ('django.db.models.fields.IntegerField', [], {}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'polytype': ('django.db.models.fields.IntegerField', [], {}),
            'soc_cnty': ('django.db.models.fields.IntegerField', [], {}),
            'st_fips': ('django.db.models.fields.IntegerField', [], {}),
            'stname': ('django.db.models.fields.CharField', [], {'max_length': '2'})
        },
        'trees.forestproperty': {
            'Meta': {'object_name': 'ForestProperty'},
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_forestproperty_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'geometry_final': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_forestproperty_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_forestproperty_related'", 'to': "orm['auth.User']"})
        },
        'trees.fvsaggregate': {
            'Meta': {'object_name': 'FVSAggregate'},
            'after_ba': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'after_merch_bdft': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'after_merch_ft3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'after_total_ft3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'after_tpa': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'age': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'agl': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bgl': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'calc_carbon': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cedr_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cedr_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ch_cf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ch_hw': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ch_tpa': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cond': ('django.db.models.fields.IntegerField', [], {}),
            'cut_type': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'dead': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'df_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'df_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'es_btl': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'firehzd': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'hw_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'hw_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lg_cf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'lg_hw': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'lg_tpa': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'lp_btl': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'merch_carbon_removed': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'merch_carbon_stored': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mnconbf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mnconhrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mnhw_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mnhw_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'nsodis': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'nsofrg': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'nsonest': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'offset': ('django.db.models.fields.IntegerField', [], {}),
            'pine_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'pine_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'pp_btl': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'removed_merch_bdft': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'removed_merch_ft3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'removed_total_ft3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'removed_tpa': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rx': ('django.db.models.fields.IntegerField', [], {}),
            'site': ('django.db.models.fields.IntegerField', [], {}),
            'sm_cf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sm_hw': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sm_tpa': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'spprich': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sppsimp': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sprc_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sprc_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'start_ba': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_merch_bdft': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_merch_ft3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_total_ft3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_tpa': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'total_stand_carbon': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'var': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'wj_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'wj_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ww_bf': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ww_hrv': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'year': ('django.db.models.fields.FloatField', [], {})
        },
        'trees.fvsspecies': {
            'AK': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'BM': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'CA': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'CI': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'CR': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'EC': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'EM': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'IE': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'KT': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'Meta': {'object_name': 'FVSSpecies'},
            'NC': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'NI': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'PN': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'SO': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'TT': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'UT': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'WC': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'WS': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'common': ('django.db.models.fields.TextField', [], {}),
            'fia': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'fvs': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'scientific': ('django.db.models.fields.TextField', [], {}),
            'usda': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'})
        },
        'trees.fvsvariant': {
            'Meta': {'object_name': 'FVSVariant'},
            'code': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'decision_tree_xml': ('django.db.models.fields.TextField', [], {'default': "''"}),
            'fvsvariant': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'trees.idbsummary': {
            'Meta': {'object_name': 'IdbSummary', 'db_table': "u'idb_summary'"},
            'acres': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'acres_vol': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'age_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'aspect_deg': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'avgofba_ft2_ac': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgofdbh_in': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgofht_ft': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgofslope': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgoftpa': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'baa_ge_3_stunits': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bac_prop': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'bah_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'calc_aspect': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'calc_slope': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cancov': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cond_id': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'}),
            'countofsubplot_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'county_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'covcl': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'elev_ft': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fia_forest_type_name': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True', 'blank': 'True'}),
            'firstofaspect_deg': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'for_type': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'for_type_name': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True', 'blank': 'True'}),
            'for_type_secdry': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'for_type_secdry_name': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True', 'blank': 'True'}),
            'forest_name': ('django.db.models.fields.CharField', [], {'max_length': '510', 'null': 'True', 'blank': 'True'}),
            'fvs_variant': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'halfstate_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'latitude_fuzz': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude_fuzz': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'mai': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'ogsi': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'own_group': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'owner': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'plant_assoc_code': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'plot_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'qmd_hwd_cm': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmd_swd_cm': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmd_tot_cm': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmda_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmda_dom_stunits': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdc_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'qmdh_dom': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sdi': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sdi_reineke': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'site_class_fia': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_index_fia': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'site_species': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sizecl': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'slope': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'stand_age': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'stand_age_even_yn': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'stand_size_class': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'state_name': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True', 'blank': 'True'}),
            'stdevofaspect_deg': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stdevofslope': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stndhgt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'stndhgt_stunits': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'struccond': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'struccondr': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sumofba_ft2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_ge_3': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tph_ge_3_stunits': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'vegclass': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vegclassr': ('django.db.models.fields.SmallIntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'trees.myrx': {
            'Meta': {'ordering': "['date_modified']", 'object_name': 'MyRx'},
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_myrx_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'default': "''"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rx': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.Rx']"}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_myrx_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_myrx_related'", 'to': "orm['auth.User']"})
        },
        'trees.rx': {
            'Meta': {'object_name': 'Rx'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'internal_desc': ('django.db.models.fields.TextField', [], {}),
            'internal_name': ('django.db.models.fields.TextField', [], {}),
            'internal_type': ('django.db.models.fields.CharField', [], {'default': "'NA'", 'max_length': '2'}),
            'variant': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.FVSVariant']"})
        },
        'trees.scenario': {
            'Meta': {'ordering': "['-date_modified']", 'object_name': 'Scenario'},
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_scenario_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'input_age_class': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'input_property': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.ForestProperty']"}),
            'input_rxs': ('trees.models.JSONField', [], {'default': "'{}'", 'null': 'True', 'blank': 'True'}),
            'input_target_boardfeet': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'input_target_carbon': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'output_scheduler_results': ('trees.models.JSONField', [], {'null': 'True', 'blank': 'True'}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_scenario_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'spatial_constraints': ('django.db.models.fields.TextField', [], {'default': "''"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_scenario_related'", 'to': "orm['auth.User']"})
        },
        'trees.scenariostand': {
            'Meta': {'object_name': 'ScenarioStand'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'cond_id': ('django.db.models.fields.BigIntegerField', [], {}),
            'constraint': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.SpatialConstraint']", 'null': 'True'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_scenariostand_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'geometry_final': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'geometry_orig': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'manipulators': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'offset': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'rx': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.Rx']"}),
            'rx_internal_num': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'scenario': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.Scenario']"}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_scenariostand_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'stand': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.Stand']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_scenariostand_related'", 'to': "orm['auth.User']"})
        },
        'trees.spatialconstraint': {
            'Meta': {'object_name': 'SpatialConstraint'},
            'category': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'default_rx': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['trees.Rx']"}),
            'geom': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'trees.stand': {
            'Meta': {'object_name': 'Stand'},
            'aspect': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'cond_id': ('django.db.models.fields.BigIntegerField', [], {'default': 'None', 'null': 'True', 'blank': 'True'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_stand_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'cost': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'elevation': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'geometry_final': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'geometry_orig': ('django.contrib.gis.db.models.fields.PolygonField', [], {'srid': '3857', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'manipulators': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'nn_savetime': ('django.db.models.fields.FloatField', [], {'default': '0.0'}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rast_savetime': ('django.db.models.fields.FloatField', [], {'default': '0.0'}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_stand_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'slope': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'strata': ('django.db.models.fields.related.ForeignKey', [], {'default': 'None', 'to': "orm['trees.Strata']", 'null': 'True', 'on_delete': 'models.SET_NULL', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_stand_related'", 'to': "orm['auth.User']"})
        },
        'trees.strata': {
            'Meta': {'object_name': 'Strata'},
            'additional_desc': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'trees_strata_related'", 'null': 'True', 'to': "orm['contenttypes.ContentType']"}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': "'255'"}),
            'object_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'search_age': ('django.db.models.fields.FloatField', [], {}),
            'search_tpa': ('django.db.models.fields.FloatField', [], {}),
            'sharing_groups': ('django.db.models.fields.related.ManyToManyField', [], {'blank': 'True', 'related_name': "'trees_strata_related'", 'null': 'True', 'symmetrical': 'False', 'to': "orm['auth.Group']"}),
            'stand_list': ('trees.models.JSONField', [], {}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'trees_strata_related'", 'to': "orm['auth.User']"})
        },
        'trees.treelivesummary': {
            'Meta': {'object_name': 'TreeliveSummary', 'db_table': "u'treelive_summary'"},
            'avgofage_bh': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgofba_ft2_ac': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgofdbh_in': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgofht_ft': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'avgoftpa': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'calc_dbh_class': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'calc_tree_count': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'class_id': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'}),
            'cond_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'count_speciessizeclasses': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fia_forest_type_name': ('django.db.models.fields.CharField', [], {'max_length': '60', 'blank': 'True'}),
            'pct_of_totalba': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'plot_id': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sumofba_ft2_ac': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'sumoftpa': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'total_ba_ft2_ac': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'varname': ('django.db.models.fields.CharField', [], {'max_length': '60', 'blank': 'True'})
        }
    }

    complete_apps = ['trees']