# Generated by Django 2.1.7 on 2019-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverystand',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='discoverystand',
            name='splash_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
