# Generated by Django 2.1.7 on 2019-04-16 13:58

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discovery', '0002_auto_20190411_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('manipulators', models.TextField(blank=True, help_text='csv list of manipulators to be applied', null=True, verbose_name='Manipulator List')),
                ('geometry_orig', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857, verbose_name='Original Polygon Geometry')),
                ('geometry_final', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857, verbose_name='Final Polygon Geometry')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('splash_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('age', models.IntegerField()),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discovery_examplestand_related', to='contenttypes.ContentType')),
                ('sharing_groups', models.ManyToManyField(blank=True, editable=False, null=True, related_name='discovery_examplestand_related', to='auth.Group', verbose_name='Share with the following groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_examplestand_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_class', models.SmallIntegerField(choices=[(0, '0" to 2"'), (2, '2" to 6"'), (6, '6" to 12"'), (12, '12" to 24"'), (24, '24" to 36"'), (36, '36" to 48"'), (48, '48" to 70"'), (70, 'Greater than 70"')])),
                ('tpa', models.SmallIntegerField()),
                ('species', models.ForeignKey(on_delete='CASCADE', to='trees.FVSSpecies')),
                ('stand', models.ForeignKey(on_delete='CASCADE', to='discovery.ExampleStand')),
            ],
        ),
    ]
