# Generated by Django 2.1.7 on 2019-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_examplestand_standlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standlistentry',
            name='species',
            field=models.CharField(max_length=255),
        ),
    ]
