# Generated by Django 2.1.7 on 2019-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_auto_20190417_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standlistentry',
            name='size_class',
            field=models.SmallIntegerField(),
        ),
    ]
