# Generated by Django 2.1.7 on 2019-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_auto_20190417_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplestand',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
