# Generated by Django 2.1.7 on 2019-04-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_examplestand_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverystand',
            name='lot_property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trees.ForestProperty'),
        ),
    ]
