# Generated by Django 2.1.7 on 2019-04-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
        ('discovery', '0008_auto_20190423_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the scenario to be created', max_length=255)),
                ('description', models.TextField(blank=True, default=None, help_text='The description to be displayed in the tooltip for selecting scenarios created from this', null=True)),
                ('show', models.BooleanField(default=False, help_text='This scenario is ready to be shown as an option for all appropriate stands')),
                ('default', models.BooleanField(default=False, help_text='This scenario should be selected automatically for display on compare page')),
            ],
        ),
        migrations.AddField(
            model_name='discoveryrx',
            name='discovery_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.DiscoveryScenario'),
        ),
        migrations.AddField(
            model_name='discoveryrx',
            name='rx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.Rx'),
        ),
        migrations.AddField(
            model_name='discoveryrx',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.FVSVariant'),
        ),
    ]
