# Generated by Django 2.2.12 on 2020-11-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_auto_20190427_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverystand',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='discovery_discoverystand_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='examplestand',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='discovery_examplestand_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
    ]
